version: '3.8'

services:
  php-httpd:
    image: php:7.3-apache
    ports:
      - 8085:80
    volumes:
      - "./DR:/var/www/html"
  
  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
        TZ: "Asia/Beirut"
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "rtpwd"
        MYSQL_USER: 'tstuser'
        MYSQL_PASSWORD: 'tstpassword'
        MYSQL_DATABASE: 'tstdb'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - 'mariadb:db'
    ports:
        - 8086:80

volumes:
  mariadb-volume: