name: LAMP_WF

on: push

jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Check out code
      with:
        repository: 'iswa-git/docker-LAMP'

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}


    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: ibrikdev/demo
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_IBRIKDEV_USER }}
        password: ${{ secrets.DOCKER_IBRIKDEV_PASSWORD }}